import NavBar from "@/components/NavBar";
import "./globals.css";
import Container from "@/components/Container";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Sass Starter Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <NavBar />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
