import NavBar from "@/components/layout/NavBar";
import "./globals.css";
import Container from "@/components/layout/Container";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Sass Starter Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className=''>
        <NavBar />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
